# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0034_auto_20170412_1453'),
        ('wagtail_embed_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedvideo',
            name='collection',
            field=models.ForeignKey(default=wagtail.wagtailcore.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='embedvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='embedvideo',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.UzmanImage', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='embedvideo',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
