# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_embed_videos', '0005_permissions_data'),
        ('wagtail_embed_videos', '0004_auto_20160911_2111'),
    ]

    operations = [
    ]
